//
//  RandomNumber.c
//  RandomNumberDemo
//
//  Created by Amit on 15/08/20.
//  Copyright © 2020 Amit. All rights reserved.
//

#include "RandomNumber.h"
#include <stdio.h>
#include <stdlib.h> 
//int generateRandomNumber(){
//    return rand();
//}

void generateRandomNumber() {
    //Test for the GMP dependency which is used by the table
//    timestamp := (int64_t)(time.Now().UnixNano())
//    snote, stempo, soctave := 2, 3, 4
//    note := (uint8)(snote)
//    tempo := (uint8)(stempo) + 1
//    octave := (uint8)(soctave)
//    primeBitSize := 24
//    desireKeySize := (uint64)(155)
//    octonionTable := octonion.NewTable()
//    trigKey, tempoKey := octonionTable.GetKeys(note, tempo, octave, timestamp, uint64(12343), primeBitSize, desireKeySize)
//    fmt.Println("TrigKey: ", trigKey)
//    fmt.Println("TempoKey: ", tempoKey)
//    //Test the openssl engine that links with the crypto comply module
//    // var openssl engine.OpenSSL
//    // openssl.Certs("random data that is generated by CrownRNG™")
//    //Test the cpu metrics generator which is a GO package that gathers cpu metrics
//    metrics := cpumetrics.Data(1000, time.Millisecond)
//    fmt.Println(metrics[0]) // print the first data ticks
}
